const mongoose = require('mongoose');
const Champion = require('../models/champion');


mongoose.connect('mongodb://localhost:27017/lol-app', {
    useNewUrlParser: true,
    useCreateIndex: true,
    useUnifiedTopology: true
})


const db = mongoose.connection;
db.on("error", console.error.bind(console, "connection error:"));
db.once("open", () => {
    console.log("Database connected!");
})






const seedDB = async() => {
    await Champion.deleteMany({});
    for(let i = 0; i < champions.length; i++){
        new Champion({
            name: `${champions[i].name}`,
            image: `${champions[i].image}`,
            numWins: `${champions[i].numWins}`,
            numLosses: `${champions[i].numLosses}`,
            notes: `${champions[i].notes}`
        })
        await champion.save();
        }
    }




const champions = [
    {
    name: "Aatrox",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/c/cc/AatroxSquare.png?version=17d10bd9faefe38daca6eb4a3abe361b",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Ahri",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/1/18/AhriSquare.png?version=b063ffe901511592494d06e363dc4dcd",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Akali",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/a/a5/AkaliSquare.png?version=b9c0616208ad791ca5d3d4970bb79154",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Alistar",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/3/34/AlistarSquare.png?version=90ed5941eceb732b02fa69579c9461ca",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Amumu",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/2/26/AmumuSquare.png?version=6eb0994e89cd62e0cc6bcd3934172108",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Anivia",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/0/01/AniviaSquare.png?version=ec94a2b62cd0c288e9724c3735d60b45",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Annie",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/6/6f/AnnieSquare.png?version=a9cb9afb85f3a8bed65f8118814f5870",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Aphelios",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/1/13/ApheliosSquare.png?version=9d7f933716b2d67240018bb615fa51a4",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Ashe",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/4/4a/AsheSquare.png?version=e6be88b600db4cf9c0950127104d48ee",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Aurelion Sol",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/c/c3/Aurelion_SolSquare.png?version=5e42637e40badb4e2016d2dee5f42518",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Azir",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/f/f7/AzirSquare.png?version=caa3b46c0cc988b87373b6a77a8d2fe4",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Bard",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/6/69/BardSquare.png?version=1d2b705d2f2210063b0f1965b839483b",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Blitzcrank",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/5/5b/BlitzcrankSquare.png?version=b50cb998148afd7bfc64678c3387a489",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Brand",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/a/ab/BrandSquare.png?version=094ba552061d3d401e7fab3b62e50927",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Braum",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/b/b6/BraumSquare.png?version=af74876be8ccaa97ba0c4a5dec7f84bf",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Caitlyn",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/e/e6/CaitlynSquare.png?version=0bb06094c28a1086fe58f39d85d05812",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Camille",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/1/13/CamilleSquare.png?version=27eaf42bcf0406577a5f792b0631b971",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Cassiopeia",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/c/ca/CassiopeiaSquare.png?version=527fb34698e4dc88ecf2435a3e015aab",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Cho'Gath",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/a/ae/Cho%27GathSquare.png?version=181bd7e699e1035a22527dd2dbe45415",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Corki",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/3/3d/CorkiSquare.png?version=413f597b58a6719676a8b5d1a543c7dc",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Darius",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/5/54/DariusSquare.png?version=85b8f660b8095781604324278d5b04f5",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Diana",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/9/90/DianaSquare.png?version=5d84ce0e02f1c1df9c6b4f056db3e686",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Dr. Mundo",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/3/35/Dr._MundoSquare.png?version=0cbb47abef8b6ca309a609246f2d285c",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Draven",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/d/d7/DravenSquare.png?version=394f50f15cc4608d8289633b307b1f31",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Ekko",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/e/ef/EkkoSquare.png?version=16e6b703ccbee9084e986ab77b9ea3d1",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Elise",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/9/91/EliseSquare.png?version=bbcd5bb490d89d8dc9c166df4177b6c5",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Evelynn",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/5/5b/EvelynnSquare.png?version=146592542c0d8e564b551704ab578490",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Ezreal",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/c/c3/EzrealSquare.png?version=20b251fff4e62e9e3bb2d8e88ba1acba",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Fiddlesticks",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/9/95/FiddlesticksSquare_Unreleased.png?version=31a38e0f79a55aa30528daa25bfdfcce",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Fiora",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/d/d2/FioraSquare.png?version=a0fe28ee06f3a53ed9a1e5eb9a9a2364",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Fizz",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/d/db/FizzSquare.png?version=246b03c497c1173321e34c8f2907678e",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Galio",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/4/40/GalioSquare.png?version=85ee6f305bbb9366cdc8f8bb4318b8bb",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Gangplank",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/f/fe/GangplankSquare.png?version=d2f4a36d063bdb842e329a55616fe102",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Garen",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/e/ea/GarenSquare.png?version=17b122cf743b1ec93dfbce2f8828c08e",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Gnar",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/6/6b/GnarSquare.png?version=c5bf0304d063710239a93f4e78ddad9a",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Gragas",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/6/67/GragasSquare.png?version=7e599cbf27235ef5575dfe02313331c1",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Graves",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/2/26/GravesSquare.png?version=dd63dc5a6cbd902bcc38d98c0e9be579",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Hecarim",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/4/4c/HecarimSquare.png?version=1ae89d21ab0a74b857522fbe4eec3dd4",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Heimerdinger",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/5/55/HeimerdingerSquare_Unreleased.png?version=ab6e0f3d129252d6d704c5643a927679",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Illaoi",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/a/a7/IllaoiSquare.png?version=fed3dd16ba9328d0269a62aef7194dc7",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Irelia",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/7/72/IreliaSquare.png?version=1f2fff44f9ef07d4230ebb450e618b43",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Ivern",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/9/9d/IvernSquare.png?version=489e26031d5e5764385cd35524008091",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Janna",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/3/3f/JannaSquare.png?version=e61b64b2443851cb8080e5f73f86373a",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Jarvan IV",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/6/6c/Jarvan_IVSquare.png?version=85186555f8079f529baf4ad51005052e",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Jax",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/0/0f/JaxSquare.png?version=20cc0e4f3272cef1ce908fedb3ba016b",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Jayce",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/a/aa/JayceSquare.png?version=82b1d16ddff378b4c0c43b7039717b06",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Jhin",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/8/8b/JhinSquare.png?version=5477f97e4e0f57e09c878f31d140d7e8",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Jinx",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/e/e2/JinxSquare.png?version=6e3f6ede43524f46964cd490a41423a6",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Kai'sa",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/4/49/Kai%27SaSquare.png?version=ef3ecd90eccbd4368ef13eb78ab0d2cb",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Kalista",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/a/aa/KalistaSquare.png?version=6005ebdd692e1c473e53e5c7afbe2ee4",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Karma",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/4/4f/KarmaSquare.png?version=b35f55e328cf1b586c2b158c662e20c3",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Karthus",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/e/e1/KarthusSquare.png?version=530ee597155c934b6d3bf738cff09399",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Kassadin",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/5/57/KassadinSquare.png?version=6231875a42a5f23d9272bc76f3b7b2bc",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Katarina",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/a/ae/KatarinaSquare.png?version=a2280833a863ad282bc7052058ee580e",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Kayle",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/b/bd/KayleSquare.png?version=c4067c9e88466fd62f7eed0d95fd2bf2",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Kayn",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/3/37/KaynSquare.png?version=bd307a4949b9ae28d443687b2af69389",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Kennen",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/6/69/KennenSquare.png?version=90a88732257e529ca97b4d91f05574fc",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Kha'Zix",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/1/14/Kha%27ZixSquare.png?version=79aedc7d47218e82e8e4cea2f8ffc9a9",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Kindred",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/6/6e/KindredSquare.png?version=2648369fd25c8c5e5f1c354407b643f5",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Kled",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/e/ef/KledSquare.png?version=7f0c9dee157a68d0e8dc15aa7c407d79",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Kog'Maw",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/4/45/Kog%27MawSquare.png?version=0facd0788c7f033ccba9519d5e7c54d7",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "LeBlanc",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/f/f1/LeBlancSquare.png?version=1b55e91e2cece412a8d3c6a7b778ab81",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Lee Sin",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/4/4f/Lee_SinSquare.png?version=63ac9e7fb9f0cd0f5076acbd2f62de75",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Leona",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/5/54/LeonaSquare.png?version=0ef92f981de35fdacb655a6f5c1e0b17",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Lillia",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/4/49/LilliaSquare.png?version=330b357c29bfbaa49edabbb72d86ec4c",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Lissandra",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/3/36/LissandraSquare.png?version=922e01fcd89806e7f73ce046a7ea8963",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Lucian",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/1/1e/LucianSquare.png?version=4ffe6e72495f2d0bf63e9808f666994f",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Lulu",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/9/91/LuluSquare.png?version=1f04e00ecf999c191140fac5ab60ff4a",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Lux",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/0/01/LuxSquare.png?version=1154db31c6d71e69032ebb5f33602b1b",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Malphite",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/6/6f/MalphiteSquare.png?version=de1ec00b6f553f1e2eccd4e29b1e5f57",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Malzahar",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/a/a7/MalzaharSquare.png?version=4e2a9be403eb8bfd00ef017313c540b6",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Maokai",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/6/64/MaokaiSquare.png?version=07f8dd2ca07b069155826955596f0568",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Master Yi",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/b/b2/Master_YiSquare.png?version=cb40d9c0cf633b209cabd22e709587da",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Miss Fortune",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/9/9d/MissFortuneSquare.png?version=a4742752980f19f6aa93b46847fe128a",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Mordekaiser",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/4/4d/MordekaiserSquare.png?version=51ee9eaa68ad8a0bcbe8fa24e8ab18d7",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Morgana",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/d/d8/MorganaSquare.png?version=69e88850753a39cc3b34e6f90f7fa5d7",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Nami",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/d/d2/NamiSquare.png?version=acb333f566b27ea358626deb1fc69b8d",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Nasus",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/5/58/NasusSquare.png?version=c436db44693086af198b30ec48bbd4a3",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Nautilus",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/b/b5/NautilusSquare.png?version=77ded0056ad0903828fe95c66a66c41f",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Neeko",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/8/88/NeekoSquare.png?version=553e6cb6c571b68c1297966f3b872374",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Nidalee",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/7/7c/NidaleeSquare.png?version=4bea0440002960b0763325e7507b4359",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Nocturne",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/6/65/NocturneSquare.png?version=628c165d3b2732bf924f26f9972f2672",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Nunu",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/b/be/Nunu_%26_WillumpSquare.png?version=88a4d5fe3b3c699340d571f1321a6b7f",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Olaf",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/2/2b/OlafSquare.png?version=7a3a21bc9355f7c76bd2f3a72ad8cbd1",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Orianna",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/b/b0/OriannaSquare.png?version=ccd32059add04895c9bdd4a8eb77be0d",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Ornn",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/3/31/OrnnSquare.png?version=4258a15b6e52565cda3c2982d9b623b0",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Pantheon",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/9/9b/PantheonSquare.png?version=585f51bf9f53a80b4fcf18a9be4d8708",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Poppy",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/e/e3/PoppySquare.png?version=19ce4af85bfe620123bfdd9de0e572bb",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Pyke",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/8/83/PykeSquare.png?version=1b9d8caa1959fca5f1dc2ac305ed612b",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Qiyana",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/c/ca/QiyanaSquare.png?version=01b1b0159a76f5ba78d9d96092e410a0",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Quinn",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/7/7c/QuinnSquare.png?version=ecb75b1ace6217309f34db8b7ff70857",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Rakan",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/8/8b/RakanSquare.png?version=82af0280cf609856f72a4176b4ee3759",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Rammus",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/7/7c/RammusSquare.png?version=9388e736061111c7f3c9cbbb524802c5",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Rek'Sai",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/3/3e/Rek%27SaiSquare.png?version=d37acc00ce9909e8b780439394b95680",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Renekton",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/f/fc/RenektonSquare.png?version=6608f6b07c800e22dce3fbe7b77c78f5",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Rengar",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/f/f1/RengarSquare.png?version=a2fab3866c224d98de2ce4cc9d7ade89",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Riven",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/4/46/RivenSquare.png?version=283e9a80fdf9743804abc4e16e43975c",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Rumble",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/1/13/RumbleSquare.png?version=110ccdaaa62faf2976d04634cec0b541",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Ryze",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/2/28/RyzeSquare.png?version=cdbeba2a91284b80a1c1a2098ce0cbdb",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Sejuani",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/9/93/SejuaniSquare.png?version=90184efded7f9d0a54e3ab8817a66a01",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Senna",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/2/21/SennaSquare.png?version=439a6b5024cbc175f91801af00fcea52",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Sett",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/1/19/SettSquare.png?version=cd05ad9766462b5994ba5afb0db6c481",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Shaco",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/9/93/ShacoSquare.png?version=dc9463e34eab5d45cebb91f6f1b54bc0",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Shen",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/d/d3/ShenSquare.png?version=8f0bd1facfc167cbbc229552ff96eb73",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Shyvana",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/f/f6/ShyvanaSquare.png?version=4b7fddf1eaf1cfb4e4ee2ed321f5a5d4",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Singed",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/9/96/SingedSquare.png?version=ee4d5697c2af97f95981ac8b65b83064",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Sion",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/6/61/SionSquare.png?version=0415f24fb516ebf2c08fa810c1aa9bc9",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Sivir",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/e/e1/SivirSquare.png?version=bec580b4f83a189e5340bdccab406228",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Skarner",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/8/80/SkarnerSquare.png?version=4634dfe9919dba13e2508d38ea773d4c",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Sona",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/5/56/SonaSquare.png?version=f163d9db14b32838364af2fa2dff884c",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Soraka",
    image: "Image will go here",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Swain",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/8/8c/SwainSquare.png?version=e2a6c69f4dc7c1d0e07a212ec7fa5197",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Sylas",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/e/eb/SylasSquare.png?version=1bf9446d786e2a397fa7da2ca23407e4",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Syndra",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/6/65/SyndraSquare.png?version=7b7470c81ba868cf587c9e63a0085139",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Tahm Kench",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/0/03/Tahm_KenchSquare.png?version=865e8d5de6f05f3863290424ab42a496",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Taliyah",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/2/2d/TaliyahSquare.png?version=4a372072e21f3f05cf89a8fcc624d278",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Talon",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/f/f9/TalonSquare.png?version=b3959365f0fe48b61252fef727fb96cb",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Taric",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/c/c4/TaricSquare.png?version=29007ea015b89b116c5d1df82371ef0f",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Teemo",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/0/04/TeemoSquare.png?version=3046ec67b5d5c387968819a57f11325e",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Thresh",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/7/7b/ThreshSquare.png?version=3db490c49eb0b4bee0e9af0b82d85a34",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Tristana",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/0/06/TristanaSquare.png?version=6e7ed0d39b42a2c0bab9e5ae08a80c3b",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Trundle",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/c/c4/TrundleSquare.png?version=6c5bba0c9752addbc0b014d1a978a60f",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Tryndamere",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/5/5f/TryndamereSquare.png?version=212a124ef6af23869dc00e752aed1063",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Twisted Fate",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/f/fb/Twisted_FateSquare.png?version=040c49ef9bfc0942da0e284482068ca4",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Twitch",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/7/79/TwitchSquare.png?version=ad87842574580929a99caa3638f2c91e",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Udyr",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/d/d1/UdyrSquare.png?version=1bb2771a28ba2e5409b26ddbbb0d67a7",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Urgot",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/8/88/UrgotSquare.png?version=c1fff78f8b485448768185cd6856e222",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Varus",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/c/c2/VarusSquare.png?version=fd9088d7016f52bf45272873264729a6",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Vayne",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/9/95/VayneSquare.png?version=3c0f63940b9154660a3db517b745688d",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Veigar",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/8/8f/VeigarSquare.png?version=5d208678d1958ee56522e1cdb7ec94f9",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Vel'koz",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/0/05/Vel%27KozSquare.png?version=222add74ec5dca30af6b675e80770b32",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Viktor",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/a/a3/ViktorSquare.png?version=f9a9cd2cf9a1faeb360184fd0556f3ee",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Vi",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/c/c0/ViSquare.png?version=b050ba90c8e20a0d54bc17cf957466a3",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Vladimir",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/7/75/VladimirSquare.png?version=f20cef89030a416dfc44e096f8f6f033",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Volibear",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/f/f9/VolibearSquare.png?version=71e6a415bfad9de8e11f8286be493d01",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Warwick",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/4/42/WarwickSquare.png?version=7cddddd7d120dcdea309841df309183b",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Wukong",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/6/6d/WukongSquare.png?version=5e4ee8ccfeffd3884d82c9f046efd53f",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Xayah",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/b/b5/XayahSquare.png?version=71719150d0ef0828808915e86f9b0155",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Xerath",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/7/7a/XerathSquare.png?version=545d1fabcf42ec41b1e190ef280e2d22",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Xin Zhao",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/6/63/Xin_ZhaoSquare.png?version=1c772a46d418dacccf126c1db0419f52",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Yasuo",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/c/c0/YasuoSquare.png?version=66c8e7f3f2ca1de0bf8a6f39e6e76fc9",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Yorick",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/d/d8/YorickSquare.png?version=9795ba447685028487867d89e1e7c345",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Yuumi",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/7/70/YuumiSquare.png?version=12d9738db2f3d707cbf59e306972d411",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Zac",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/8/81/ZacSquare.png?version=e8de5cb4aa1c0bcb39bb6a931dc90fdd",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Zed",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/b/bb/ZedSquare.png?version=956f87c939020b1bc1a2dd3033aa030b",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Ziggs",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/5/55/ZiggsSquare.png?version=c3f54fc756067c405ca2eceeab658412",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Zilean",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/a/ac/ZileanSquare.png?version=e333aa16e11ff4fdf892241f905bc96d",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Zoe",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/b/b8/ZoeSquare.png?version=20bc09112cf15b60a7653f7af1f4897c",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    },
    {
    name: "Zyra",
    image: "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/1/1a/ZyraSquare.png?version=c61ef2aec966e5f6a90706621b101844",
    numWins: 0,
    numLosses: 0,
    notes:"Notes will go here", 
    }
]


seedDB();